### ISSUE TITLE
No member 'timestamp'

### ISSUE THREAD

**Issue by ghost** [playfultechnology/esp32-cam#1]
Trying to compile esp32-cam in Arduino IDE 1.8.15. I have installed ESP Mail Client V1.1.6. I get an exit status 1 withthis message:
C:\Users\bruce\OneDrive\Documents\Arduino\esp32-cam-main\code\esp32-cam\esp32-cam.ino: In function 'void smtpCallback(SMTP_Status)':
esp32-cam:103:27: error: 'SMTP_Result {aka struct esp_mail_smtp_send_status_t}' has no member named 'timestamp'
       localtime_r(&result.timestamp, &dt);

Thanks

**Comment by zapper44** [comment]
The latest commit seems to want to correct a typo on line 103, but the member name is indeed 'timesstamp' (with two s-es) for ESP Mail Client version 1.1.6. After changing it back to 'timesstamp' it compiles successfully on Arduino 1.8.10 with ESP mail client v1.1.6.

ESP Mail Client Version 1.2.0 also compiles fine with 'timesstamp'.

ESP Mail Client Version 1.3.0 trips over the apparently misspelled 'timesstamp', but after correcting this to 'timestamp' it now fails to compile with the following error message: 
   "invalid conversion from 'uint32_t* {aka unsigned int*}' to 'const time_t* {aka const long int*}' [-fpermissive]"

Best to stick with ESP Mail Client version 1.1.6 but don't go higher than version 1.2.0.

**Comment by alastaira** [comment]
Thanks for the report, Zapper44, I've just committed a new release that uses the latest version of ESP Mail (v1.6.4 of ESP_Mail library).
