### ISSUE TITLE
Flash LED doesn't come on after sleep

### ISSUE THREAD

**Issue by ScruffR** [playfultechnology/esp32-cam#2]
Since the `sleep()` function calls
```
  // Ensure the flash stays off while we sleep
  rtc_gpio_hold_en(GPIO_NUM_4);
```
any subsequent attempt to modify the pin settings will fail, resulting in the flash LED not coming back on again.
To solve that you'd just need to execute `rtc_gpio_hold_dis(GPIO_NUM_4);` before trying to setup the pin again.

**Comment by alastaira** [comment]
Fixed in 951f9d8 - cheers!
