### ISSUE TITLE
'class ESP_Mail_Client' has no member named 'sdBegin'

### ISSUE THREAD

**Issue by Zaxxore** [playfultechnology/esp32-cam#3]
I try to compile your sketch esp32-cam.ino as it is and I get that error message:
'class ESP_Mail_Client' has no member named 'sdBegin'

I'm using Arduino IDE 1.8.13, ESP_MAIL_CLIENT 2.1.3 and ESP32 2.0.2

Any ideas of the problem ?

**Comment by Till437** [comment]
I sadly have the same problem and can not find a fix.

**Comment by Zaxxore** [comment]
I finaly found a fix. Use ESP_MAIL_CLIENT version 1.2.0 and at about line 108 instead of result.timestamp put result.timesstamp (2s in the midle). Try that and let me know.

**Comment by Till437** [comment]
Oh wow works like a charm, thank you so much! This is my first ever DIY Project and it is so much fun yet so confusing at times.

**Comment by Zaxxore** [comment]
Fixed!
